/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PartnerDashboardRouteImport } from './routes/partner-dashboard'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as InvestorsRouteImport } from './routes/investors'
import { Route as GetStartedRouteImport } from './routes/get-started'
import { Route as FoundersRouteImport } from './routes/founders'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AppRouteImport } from './routes/app'
import { Route as AffiliateRouteImport } from './routes/affiliate'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as DealSlugRouteImport } from './routes/deal.$slug'
import { Route as AppToolsRouteImport } from './routes/app.tools'
import { Route as AppStartupsRouteImport } from './routes/app.startups'
import { Route as AppReadinessRouteImport } from './routes/app.readiness'
import { Route as AppPitchRouteImport } from './routes/app.pitch'
import { Route as AppMatchRouteImport } from './routes/app.match'
import { Route as AppInvestorsRouteImport } from './routes/app.investors'
import { Route as AppIntelligenceRouteImport } from './routes/app.intelligence'
import { Route as AppBrowseStartupsRouteImport } from './routes/app.browse-startups'
import { Route as ApiPublicCashfreeWebhookRouteImport } from './routes/api/public/cashfree-webhook'

const PartnerDashboardRoute = PartnerDashboardRouteImport.update({
  id: '/partner-dashboard',
  path: '/partner-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorsRoute = InvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => rootRouteImport,
} as any)
const GetStartedRoute = GetStartedRouteImport.update({
  id: '/get-started',
  path: '/get-started',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundersRoute = FoundersRouteImport.update({
  id: '/founders',
  path: '/founders',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateRoute = AffiliateRouteImport.update({
  id: '/affiliate',
  path: '/affiliate',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const DealSlugRoute = DealSlugRouteImport.update({
  id: '/deal/$slug',
  path: '/deal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppToolsRoute = AppToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AppRoute,
} as any)
const AppStartupsRoute = AppStartupsRouteImport.update({
  id: '/startups',
  path: '/startups',
  getParentRoute: () => AppRoute,
} as any)
const AppReadinessRoute = AppReadinessRouteImport.update({
  id: '/readiness',
  path: '/readiness',
  getParentRoute: () => AppRoute,
} as any)
const AppPitchRoute = AppPitchRouteImport.update({
  id: '/pitch',
  path: '/pitch',
  getParentRoute: () => AppRoute,
} as any)
const AppMatchRoute = AppMatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestorsRoute = AppInvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => AppRoute,
} as any)
const AppIntelligenceRoute = AppIntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => AppRoute,
} as any)
const AppBrowseStartupsRoute = AppBrowseStartupsRouteImport.update({
  id: '/browse-startups',
  path: '/browse-startups',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicCashfreeWebhookRoute =
  ApiPublicCashfreeWebhookRouteImport.update({
    id: '/api/public/cashfree-webhook',
    path: '/api/public/cashfree-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/affiliate': typeof AffiliateRoute
  '/app': typeof AppRouteWithChildren
  '/contact': typeof ContactRoute
  '/founders': typeof FoundersRoute
  '/get-started': typeof GetStartedRoute
  '/investors': typeof InvestorsRoute
  '/marketplace': typeof MarketplaceRoute
  '/partner-dashboard': typeof PartnerDashboardRoute
  '/app/browse-startups': typeof AppBrowseStartupsRoute
  '/app/intelligence': typeof AppIntelligenceRoute
  '/app/investors': typeof AppInvestorsRoute
  '/app/match': typeof AppMatchRoute
  '/app/pitch': typeof AppPitchRoute
  '/app/readiness': typeof AppReadinessRoute
  '/app/startups': typeof AppStartupsRoute
  '/app/tools': typeof AppToolsRoute
  '/deal/$slug': typeof DealSlugRoute
  '/app/': typeof AppIndexRoute
  '/api/public/cashfree-webhook': typeof ApiPublicCashfreeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/affiliate': typeof AffiliateRoute
  '/contact': typeof ContactRoute
  '/founders': typeof FoundersRoute
  '/get-started': typeof GetStartedRoute
  '/investors': typeof InvestorsRoute
  '/marketplace': typeof MarketplaceRoute
  '/partner-dashboard': typeof PartnerDashboardRoute
  '/app/browse-startups': typeof AppBrowseStartupsRoute
  '/app/intelligence': typeof AppIntelligenceRoute
  '/app/investors': typeof AppInvestorsRoute
  '/app/match': typeof AppMatchRoute
  '/app/pitch': typeof AppPitchRoute
  '/app/readiness': typeof AppReadinessRoute
  '/app/startups': typeof AppStartupsRoute
  '/app/tools': typeof AppToolsRoute
  '/deal/$slug': typeof DealSlugRoute
  '/app': typeof AppIndexRoute
  '/api/public/cashfree-webhook': typeof ApiPublicCashfreeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/affiliate': typeof AffiliateRoute
  '/app': typeof AppRouteWithChildren
  '/contact': typeof ContactRoute
  '/founders': typeof FoundersRoute
  '/get-started': typeof GetStartedRoute
  '/investors': typeof InvestorsRoute
  '/marketplace': typeof MarketplaceRoute
  '/partner-dashboard': typeof PartnerDashboardRoute
  '/app/browse-startups': typeof AppBrowseStartupsRoute
  '/app/intelligence': typeof AppIntelligenceRoute
  '/app/investors': typeof AppInvestorsRoute
  '/app/match': typeof AppMatchRoute
  '/app/pitch': typeof AppPitchRoute
  '/app/readiness': typeof AppReadinessRoute
  '/app/startups': typeof AppStartupsRoute
  '/app/tools': typeof AppToolsRoute
  '/deal/$slug': typeof DealSlugRoute
  '/app/': typeof AppIndexRoute
  '/api/public/cashfree-webhook': typeof ApiPublicCashfreeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/affiliate'
    | '/app'
    | '/contact'
    | '/founders'
    | '/get-started'
    | '/investors'
    | '/marketplace'
    | '/partner-dashboard'
    | '/app/browse-startups'
    | '/app/intelligence'
    | '/app/investors'
    | '/app/match'
    | '/app/pitch'
    | '/app/readiness'
    | '/app/startups'
    | '/app/tools'
    | '/deal/$slug'
    | '/app/'
    | '/api/public/cashfree-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/affiliate'
    | '/contact'
    | '/founders'
    | '/get-started'
    | '/investors'
    | '/marketplace'
    | '/partner-dashboard'
    | '/app/browse-startups'
    | '/app/intelligence'
    | '/app/investors'
    | '/app/match'
    | '/app/pitch'
    | '/app/readiness'
    | '/app/startups'
    | '/app/tools'
    | '/deal/$slug'
    | '/app'
    | '/api/public/cashfree-webhook'
  id:
    | '__root__'
    | '/'
    | '/affiliate'
    | '/app'
    | '/contact'
    | '/founders'
    | '/get-started'
    | '/investors'
    | '/marketplace'
    | '/partner-dashboard'
    | '/app/browse-startups'
    | '/app/intelligence'
    | '/app/investors'
    | '/app/match'
    | '/app/pitch'
    | '/app/readiness'
    | '/app/startups'
    | '/app/tools'
    | '/deal/$slug'
    | '/app/'
    | '/api/public/cashfree-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AffiliateRoute: typeof AffiliateRoute
  AppRoute: typeof AppRouteWithChildren
  ContactRoute: typeof ContactRoute
  FoundersRoute: typeof FoundersRoute
  GetStartedRoute: typeof GetStartedRoute
  InvestorsRoute: typeof InvestorsRoute
  MarketplaceRoute: typeof MarketplaceRoute
  PartnerDashboardRoute: typeof PartnerDashboardRoute
  DealSlugRoute: typeof DealSlugRoute
  ApiPublicCashfreeWebhookRoute: typeof ApiPublicCashfreeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/partner-dashboard': {
      id: '/partner-dashboard'
      path: '/partner-dashboard'
      fullPath: '/partner-dashboard'
      preLoaderRoute: typeof PartnerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investors': {
      id: '/investors'
      path: '/investors'
      fullPath: '/investors'
      preLoaderRoute: typeof InvestorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-started': {
      id: '/get-started'
      path: '/get-started'
      fullPath: '/get-started'
      preLoaderRoute: typeof GetStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founders': {
      id: '/founders'
      path: '/founders'
      fullPath: '/founders'
      preLoaderRoute: typeof FoundersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate': {
      id: '/affiliate'
      path: '/affiliate'
      fullPath: '/affiliate'
      preLoaderRoute: typeof AffiliateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/deal/$slug': {
      id: '/deal/$slug'
      path: '/deal/$slug'
      fullPath: '/deal/$slug'
      preLoaderRoute: typeof DealSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/tools': {
      id: '/app/tools'
      path: '/tools'
      fullPath: '/app/tools'
      preLoaderRoute: typeof AppToolsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/startups': {
      id: '/app/startups'
      path: '/startups'
      fullPath: '/app/startups'
      preLoaderRoute: typeof AppStartupsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/readiness': {
      id: '/app/readiness'
      path: '/readiness'
      fullPath: '/app/readiness'
      preLoaderRoute: typeof AppReadinessRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pitch': {
      id: '/app/pitch'
      path: '/pitch'
      fullPath: '/app/pitch'
      preLoaderRoute: typeof AppPitchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/match': {
      id: '/app/match'
      path: '/match'
      fullPath: '/app/match'
      preLoaderRoute: typeof AppMatchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/investors': {
      id: '/app/investors'
      path: '/investors'
      fullPath: '/app/investors'
      preLoaderRoute: typeof AppInvestorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/intelligence': {
      id: '/app/intelligence'
      path: '/intelligence'
      fullPath: '/app/intelligence'
      preLoaderRoute: typeof AppIntelligenceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/browse-startups': {
      id: '/app/browse-startups'
      path: '/browse-startups'
      fullPath: '/app/browse-startups'
      preLoaderRoute: typeof AppBrowseStartupsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/cashfree-webhook': {
      id: '/api/public/cashfree-webhook'
      path: '/api/public/cashfree-webhook'
      fullPath: '/api/public/cashfree-webhook'
      preLoaderRoute: typeof ApiPublicCashfreeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppBrowseStartupsRoute: typeof AppBrowseStartupsRoute
  AppIntelligenceRoute: typeof AppIntelligenceRoute
  AppInvestorsRoute: typeof AppInvestorsRoute
  AppMatchRoute: typeof AppMatchRoute
  AppPitchRoute: typeof AppPitchRoute
  AppReadinessRoute: typeof AppReadinessRoute
  AppStartupsRoute: typeof AppStartupsRoute
  AppToolsRoute: typeof AppToolsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBrowseStartupsRoute: AppBrowseStartupsRoute,
  AppIntelligenceRoute: AppIntelligenceRoute,
  AppInvestorsRoute: AppInvestorsRoute,
  AppMatchRoute: AppMatchRoute,
  AppPitchRoute: AppPitchRoute,
  AppReadinessRoute: AppReadinessRoute,
  AppStartupsRoute: AppStartupsRoute,
  AppToolsRoute: AppToolsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AffiliateRoute: AffiliateRoute,
  AppRoute: AppRouteWithChildren,
  ContactRoute: ContactRoute,
  FoundersRoute: FoundersRoute,
  GetStartedRoute: GetStartedRoute,
  InvestorsRoute: InvestorsRoute,
  MarketplaceRoute: MarketplaceRoute,
  PartnerDashboardRoute: PartnerDashboardRoute,
  DealSlugRoute: DealSlugRoute,
  ApiPublicCashfreeWebhookRoute: ApiPublicCashfreeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
